import type {
  Agent,
  CompanyMetrics,
  Employee,
  HealthDomain,
  MemoryRecord,
  Objective,
  Project,
  Task,
} from "./types";

export const company = {
  name: "SAI COMPANY",
  legalName: "InnovateAegis",
  tagline: "The Operating System That Runs a Company",
  mission:
    "A digital organization where founders, employees, and AI agents collaborate to build products, manage operations, make decisions, retain knowledge, and grow the company.",
};

export const metrics: CompanyMetrics = {
  activeProjects: 4,
  employeesOnline: 6,
  agentsActive: 14,
  revenue: 248000,
  revenueDeltaPct: 12.4,
  releasesThisQuarter: 9,
  openIssues: 23,
  organizationHealthScore: 82,
};

export const healthDomains: HealthDomain[] = [
  {
    key: "engineering",
    label: "Engineering Health",
    status: "green",
    score: 88,
    explanation:
      "Throughput is stable, code review queue is under 4 hours, and no critical regressions in the last release.",
  },
  {
    key: "product",
    label: "Product Health",
    status: "green",
    score: 84,
    explanation:
      "Roadmap is aligned with objectives. Sentra Deployment Module and Unite are on track for this quarter.",
  },
  {
    key: "revenue",
    label: "Revenue Health",
    status: "yellow",
    score: 71,
    explanation:
      "Pipeline is healthy but two enterprise deals slipped a cycle. Net revenue retention holding at 108%.",
  },
  {
    key: "customer",
    label: "Customer Health",
    status: "green",
    score: 86,
    explanation:
      "CSAT at 4.6/5. Three high-value feature requests captured and routed to the product roadmap.",
  },
  {
    key: "operations",
    label: "Operations Health",
    status: "yellow",
    score: 69,
    explanation:
      "One engineer is overloaded and the QA queue is growing. Team Orchestrator is rebalancing workload.",
  },
  {
    key: "knowledge",
    label: "Knowledge Health",
    status: "green",
    score: 90,
    explanation:
      "Decision and engineering memory is current. 94% of shipped work has an archived knowledge record.",
  },
];

export const objectives: Objective[] = [
  {
    id: "obj-1",
    title: "Build Sentra Software Deployment Module",
    status: "in-progress",
    progress: 62,
    owner: "Owner",
    projectSlug: "sentra-deployment",
    description:
      "Ship a controlled deployment module for Sentra that lets IT teams roll out, monitor, and roll back software across endpoints.",
  },
  {
    id: "obj-2",
    title: "Launch Unite collaboration product",
    status: "in-progress",
    progress: 38,
    owner: "Owner",
    projectSlug: "unite-launch",
    description:
      "Bring Unite from architecture to a public beta, establishing a new collaboration surface for the InnovateAegis ecosystem.",
  },
  {
    id: "obj-3",
    title: "Reach 99.95% attendance recognition accuracy on FaceNova",
    status: "in-progress",
    progress: 74,
    owner: "Owner",
    projectSlug: "facenova-accuracy",
    description:
      "Improve recognition pipeline accuracy and reduce false rejects across multi-camera deployments.",
  },
  {
    id: "obj-4",
    title: "Grow quarterly revenue by 20%",
    status: "planned",
    progress: 15,
    owner: "Owner",
    description:
      "Expand the enterprise pipeline and convert HYGYR free users into the broader product ecosystem.",
  },
];

export const employees: Employee[] = [
  {
    id: "emp-1",
    slug: "aarav-mehta",
    name: "Aarav Mehta",
    role: "Senior Software Engineer",
    department: "Engineering",
    presence: "online",
    initials: "AM",
    joined: "2024-02-11",
    responsibilities: [
      "Owns the Sentra deployment pipeline",
      "Leads backend architecture reviews",
      "Mentors mid-level engineers",
    ],
    skills: ["TypeScript", "Go", "Distributed Systems", "PostgreSQL", "Kubernetes"],
    currentWork: [
      "Implementing rollback engine for Sentra Deployment Module",
      "Reviewing API contracts with Solution Architect Agent",
    ],
    completedWork: [
      "Endpoint inventory sync service",
      "Policy enforcement engine v2",
    ],
    metrics: {
      tasksCompleted: 142,
      onTimeRate: 0.91,
      activeTasks: 5,
      knowledgeContributions: 28,
    },
    memory: ["mem-eng-1", "mem-dec-2"],
  },
  {
    id: "emp-2",
    slug: "lena-okoye",
    name: "Lena Okoye",
    role: "QA Engineer",
    department: "Quality",
    presence: "online",
    initials: "LO",
    joined: "2024-05-03",
    responsibilities: [
      "Builds regression suites for FaceNova",
      "Owns release acceptance verification",
    ],
    skills: ["Playwright", "Test Strategy", "Python", "Performance Testing"],
    currentWork: ["Validating FaceNova multi-camera accuracy benchmarks"],
    completedWork: ["Sentra audit-log regression suite", "HYGYR export test plan"],
    metrics: {
      tasksCompleted: 98,
      onTimeRate: 0.95,
      activeTasks: 4,
      knowledgeContributions: 19,
    },
    memory: ["mem-eng-2"],
  },
  {
    id: "emp-3",
    slug: "diego-ramos",
    name: "Diego Ramos",
    role: "Product Manager",
    department: "Product",
    presence: "away",
    initials: "DR",
    joined: "2023-11-20",
    responsibilities: [
      "Owns the Unite product roadmap",
      "Translates objectives into requirements with the PM Agent",
    ],
    skills: ["Product Strategy", "User Research", "Roadmapping", "Analytics"],
    currentWork: ["Defining Unite beta scope", "Prioritising customer requests"],
    completedWork: ["Sentra deployment PRD", "FaceNova v3 release plan"],
    metrics: {
      tasksCompleted: 64,
      onTimeRate: 0.88,
      activeTasks: 6,
      knowledgeContributions: 31,
    },
    memory: ["mem-prod-1", "mem-cust-1"],
  },
  {
    id: "emp-4",
    slug: "sofia-haddad",
    name: "Sofia Haddad",
    role: "DevOps Engineer",
    department: "Engineering",
    presence: "online",
    initials: "SH",
    joined: "2024-01-15",
    responsibilities: [
      "Owns CI/CD and release infrastructure",
      "Maintains monitoring and rollback tooling",
    ],
    skills: ["Terraform", "AWS", "CI/CD", "Observability", "Docker"],
    currentWork: ["Hardening the Sentra release pipeline"],
    completedWork: ["Zero-downtime deploy strategy", "Centralised logging stack"],
    metrics: {
      tasksCompleted: 110,
      onTimeRate: 0.93,
      activeTasks: 3,
      knowledgeContributions: 22,
    },
    memory: ["mem-eng-3"],
  },
  {
    id: "emp-5",
    slug: "noah-bennett",
    name: "Noah Bennett",
    role: "Sales Executive",
    department: "Sales",
    presence: "online",
    initials: "NB",
    joined: "2023-09-01",
    responsibilities: [
      "Owns enterprise pipeline for Sentra and FaceNova",
      "Runs discovery and demo cycles",
    ],
    skills: ["Enterprise Sales", "Negotiation", "Pipeline Management"],
    currentWork: ["Closing two enterprise Sentra deals"],
    completedWork: ["FaceNova multi-site rollout deal", "Q1 expansion targets"],
    metrics: {
      tasksCompleted: 47,
      onTimeRate: 0.82,
      activeTasks: 7,
      knowledgeContributions: 9,
    },
    memory: ["mem-biz-1"],
  },
  {
    id: "emp-6",
    slug: "priya-nair",
    name: "Priya Nair",
    role: "HR & People Lead",
    department: "People",
    presence: "online",
    initials: "PN",
    joined: "2023-07-12",
    responsibilities: [
      "Owns hiring and onboarding",
      "Tracks performance and team wellbeing",
    ],
    skills: ["Talent Acquisition", "People Ops", "Performance Coaching"],
    currentWork: ["Hiring a second QA engineer", "Quarterly performance reviews"],
    completedWork: ["Engineering onboarding playbook", "Compensation review"],
    metrics: {
      tasksCompleted: 53,
      onTimeRate: 0.9,
      activeTasks: 2,
      knowledgeContributions: 14,
    },
    memory: [],
  },
  {
    id: "emp-7",
    slug: "marcus-feld",
    name: "Marcus Feld",
    role: "Marketing Manager",
    department: "Marketing",
    presence: "offline",
    initials: "MF",
    joined: "2024-03-28",
    responsibilities: [
      "Owns brand and growth campaigns",
      "Manages content and launch messaging",
    ],
    skills: ["Content Strategy", "Growth Marketing", "Brand", "SEO"],
    currentWork: ["Planning the Unite launch campaign"],
    completedWork: ["HYGYR acquisition campaign", "Sentra positioning refresh"],
    metrics: {
      tasksCompleted: 38,
      onTimeRate: 0.85,
      activeTasks: 4,
      knowledgeContributions: 11,
    },
    memory: ["mem-biz-2"],
  },
];

export const agents: Agent[] = [
  {
    id: "agt-ceo",
    slug: "ceo-agent",
    name: "CEO Agent",
    role: "Chief Executive Intelligence",
    category: "executive",
    status: "active",
    tagline: "Responsible for company growth.",
    responsibilities: [
      "Tracks revenue and opportunities",
      "Monitors market trends and business risks",
      "Surfaces product opportunities",
      "Provides recommendations to the owner",
    ],
    memory: ["mem-biz-1", "mem-biz-2"],
    metrics: { tasksHandled: 312, accuracy: 0.92, autonomy: 0.6, decisionsLogged: 88 },
    assignedProjects: ["sentra-deployment", "unite-launch"],
  },
  {
    id: "agt-coo",
    slug: "coo-agent",
    name: "COO Agent",
    role: "Chief Operating Intelligence",
    category: "operations",
    status: "active",
    tagline: "Responsible for operations.",
    responsibilities: [
      "Tracks team productivity",
      "Optimises resource allocation",
      "Monitors delivery performance",
    ],
    memory: ["mem-dec-1"],
    metrics: { tasksHandled: 268, accuracy: 0.9, autonomy: 0.7, decisionsLogged: 64 },
    assignedProjects: ["sentra-deployment", "facenova-accuracy"],
  },
  {
    id: "agt-pm",
    slug: "product-manager-agent",
    name: "Product Manager Agent",
    role: "Product Definition",
    category: "product",
    status: "active",
    tagline: "Converts objectives into features.",
    responsibilities: [
      "Creates product requirements",
      "Writes user stories",
      "Defines acceptance criteria",
    ],
    memory: ["mem-prod-1"],
    metrics: { tasksHandled: 174, accuracy: 0.89, autonomy: 0.75, decisionsLogged: 41 },
    assignedProjects: ["unite-launch", "sentra-deployment"],
  },
  {
    id: "agt-architect",
    slug: "solution-architect-agent",
    name: "Solution Architect Agent",
    role: "Systems Design",
    category: "engineering",
    status: "active",
    tagline: "Designs systems before development begins.",
    responsibilities: [
      "Produces architecture diagrams",
      "Designs databases and API contracts",
      "Defines security models and scaling plans",
    ],
    memory: ["mem-eng-1", "mem-dec-2"],
    metrics: { tasksHandled: 132, accuracy: 0.94, autonomy: 0.65, decisionsLogged: 52 },
    assignedProjects: ["sentra-deployment", "unite-launch"],
  },
  {
    id: "agt-projectmanager",
    slug: "project-manager-agent",
    name: "Project Manager Agent",
    role: "Delivery Management",
    category: "operations",
    status: "active",
    tagline: "Responsible for delivery.",
    responsibilities: [
      "Tracks timelines and dependencies",
      "Manages risks and progress",
      "Knows who owns every task",
    ],
    memory: [],
    metrics: { tasksHandled: 220, accuracy: 0.91, autonomy: 0.78, decisionsLogged: 37 },
    assignedProjects: ["sentra-deployment", "unite-launch", "facenova-accuracy"],
  },
  {
    id: "agt-orchestrator",
    slug: "team-orchestrator-agent",
    name: "Team Orchestrator Agent",
    role: "Work Routing",
    category: "operations",
    status: "active",
    tagline: "Routes work automatically.",
    responsibilities: [
      "Assigns tasks to the right owners",
      "Balances workload across the team",
      "Tracks dependencies and handles escalation",
    ],
    memory: ["mem-dec-1"],
    metrics: { tasksHandled: 410, accuracy: 0.93, autonomy: 0.85, decisionsLogged: 96 },
    assignedProjects: ["sentra-deployment", "unite-launch", "facenova-accuracy"],
  },
  {
    id: "agt-engineer",
    slug: "software-engineer-agent",
    name: "Software Engineer Agent",
    role: "Implementation",
    category: "engineering",
    status: "active",
    tagline: "Builds solutions.",
    responsibilities: [
      "Implements features and fixes bugs",
      "Maintains memory of code ownership and technical decisions",
      "Collaborates with human engineers",
    ],
    memory: ["mem-eng-1", "mem-eng-3"],
    metrics: { tasksHandled: 356, accuracy: 0.88, autonomy: 0.7, decisionsLogged: 73 },
    assignedProjects: ["sentra-deployment", "facenova-accuracy"],
  },
  {
    id: "agt-qa",
    slug: "qa-engineer-agent",
    name: "QA Engineer Agent",
    role: "Quality Verification",
    category: "quality",
    status: "active",
    tagline: "Tests everything.",
    responsibilities: [
      "Creates test plans and runs validation",
      "Files bug reports and regression tests",
      "Approves or rejects work at acceptance",
    ],
    memory: ["mem-eng-2"],
    metrics: { tasksHandled: 289, accuracy: 0.95, autonomy: 0.72, decisionsLogged: 58 },
    assignedProjects: ["facenova-accuracy", "sentra-deployment"],
  },
  {
    id: "agt-devops",
    slug: "devops-agent",
    name: "DevOps Agent",
    role: "Deployment & Infrastructure",
    category: "operations",
    status: "active",
    tagline: "Handles deployment.",
    responsibilities: [
      "Manages infrastructure and CI/CD",
      "Monitors releases and handles rollbacks",
    ],
    memory: ["mem-eng-3"],
    metrics: { tasksHandled: 198, accuracy: 0.92, autonomy: 0.8, decisionsLogged: 44 },
    assignedProjects: ["sentra-deployment"],
  },
  {
    id: "agt-security",
    slug: "security-agent",
    name: "Security Agent",
    role: "Security & Compliance",
    category: "security",
    status: "active",
    tagline: "Protects the company.",
    responsibilities: [
      "Detects vulnerabilities",
      "Runs security reviews and compliance checks",
      "Performs risk analysis",
    ],
    memory: ["mem-dec-2"],
    metrics: { tasksHandled: 121, accuracy: 0.96, autonomy: 0.68, decisionsLogged: 39 },
    assignedProjects: ["sentra-deployment", "unite-launch"],
  },
  {
    id: "agt-docs",
    slug: "documentation-agent",
    name: "Documentation Agent",
    role: "Knowledge & Docs",
    category: "knowledge",
    status: "active",
    tagline: "Keeps knowledge alive.",
    responsibilities: [
      "Maintains technical, user and architecture docs",
      "Writes release notes",
    ],
    memory: ["mem-eng-1", "mem-prod-1"],
    metrics: { tasksHandled: 167, accuracy: 0.94, autonomy: 0.82, decisionsLogged: 12 },
    assignedProjects: ["sentra-deployment", "unite-launch", "facenova-accuracy"],
  },
  {
    id: "agt-cs",
    slug: "customer-success-agent",
    name: "Customer Success Agent",
    role: "Customer Memory",
    category: "growth",
    status: "active",
    tagline: "Champions the customer.",
    responsibilities: [
      "Tracks customer issues and feature requests",
      "Monitors satisfaction",
      "Maintains customer memory",
    ],
    memory: ["mem-cust-1"],
    metrics: { tasksHandled: 203, accuracy: 0.9, autonomy: 0.74, decisionsLogged: 28 },
    assignedProjects: ["facenova-accuracy"],
  },
  {
    id: "agt-sales",
    slug: "sales-agent",
    name: "Sales Agent",
    role: "Revenue Pipeline",
    category: "growth",
    status: "active",
    tagline: "Grows the pipeline.",
    responsibilities: [
      "Tracks leads, opportunities and prospects",
      "Manages the revenue pipeline",
    ],
    memory: ["mem-biz-1"],
    metrics: { tasksHandled: 156, accuracy: 0.87, autonomy: 0.66, decisionsLogged: 21 },
    assignedProjects: [],
  },
  {
    id: "agt-marketing",
    slug: "marketing-agent",
    name: "Marketing Agent",
    role: "Growth & Brand",
    category: "growth",
    status: "active",
    tagline: "Builds the brand.",
    responsibilities: [
      "Runs campaigns and content",
      "Drives growth activities",
      "Monitors brand",
    ],
    memory: ["mem-biz-2"],
    metrics: { tasksHandled: 134, accuracy: 0.86, autonomy: 0.7, decisionsLogged: 17 },
    assignedProjects: ["unite-launch"],
  },
  {
    id: "agt-hr",
    slug: "hr-agent",
    name: "HR Agent",
    role: "People Intelligence",
    category: "people",
    status: "active",
    tagline: "Supports the team.",
    responsibilities: [
      "Tracks employees and performance",
      "Surfaces hiring needs and training",
    ],
    memory: [],
    metrics: { tasksHandled: 88, accuracy: 0.91, autonomy: 0.64, decisionsLogged: 15 },
    assignedProjects: [],
  },
];

export const projects: Project[] = [
  {
    id: "prj-1",
    slug: "sentra-deployment",
    name: "Sentra Software Deployment Module",
    product: "Sentra",
    status: "active",
    health: "green",
    progress: 62,
    owner: "Aarav Mehta",
    objective: "Build Sentra Software Deployment Module",
    summary:
      "A controlled deployment module that lets IT teams roll out, monitor, and roll back software across endpoints with full auditability.",
    start: "2026-04-01",
    target: "2026-07-15",
    risks: [
      "Rollback engine depends on the new policy service",
      "QA capacity is tight while FaceNova benchmarks run in parallel",
    ],
    team: ["aarav-mehta", "sofia-haddad", "lena-okoye"],
    agents: [
      "product-manager-agent",
      "solution-architect-agent",
      "software-engineer-agent",
      "qa-engineer-agent",
      "devops-agent",
      "security-agent",
    ],
    artifacts: [
      { label: "Requirement Document", status: "done", detail: "Approved by Owner and PM Agent." },
      { label: "Product Plan", status: "done", detail: "Scope locked for v1 deployment module." },
      { label: "Architecture", status: "done", detail: "Rollback engine + policy service contracts defined." },
      { label: "Tasks", status: "in-progress", detail: "18 of 29 tasks complete." },
      { label: "Test Plans", status: "in-progress", detail: "Regression suite 70% authored." },
      { label: "Release", status: "pending", detail: "Targeted for mid-July." },
    ],
  },
  {
    id: "prj-2",
    slug: "unite-launch",
    name: "Unite Collaboration Beta",
    product: "Unite",
    status: "planning",
    health: "yellow",
    progress: 38,
    owner: "Diego Ramos",
    objective: "Launch Unite collaboration product",
    summary:
      "A new collaboration surface for the InnovateAegis ecosystem, moving from architecture to a public beta.",
    start: "2026-05-10",
    target: "2026-09-01",
    risks: [
      "Architecture still being finalised by the Solution Architect Agent",
      "Marketing launch plan not yet locked",
    ],
    team: ["diego-ramos", "marcus-feld"],
    agents: [
      "product-manager-agent",
      "solution-architect-agent",
      "marketing-agent",
      "documentation-agent",
      "security-agent",
    ],
    artifacts: [
      { label: "Requirement Document", status: "done", detail: "Beta scope drafted with PM Agent." },
      { label: "Product Plan", status: "in-progress", detail: "Roadmap for beta being sequenced." },
      { label: "Architecture", status: "in-progress", detail: "Realtime sync design in review." },
      { label: "Tasks", status: "pending", detail: "Awaiting architecture sign-off." },
      { label: "Test Plans", status: "pending", detail: "Not started." },
      { label: "Release", status: "pending", detail: "Beta targeted for September." },
    ],
  },
  {
    id: "prj-3",
    slug: "facenova-accuracy",
    name: "FaceNova Recognition Accuracy",
    product: "FaceNova",
    status: "active",
    health: "green",
    progress: 74,
    owner: "Lena Okoye",
    objective: "Reach 99.95% attendance recognition accuracy on FaceNova",
    summary:
      "Improve recognition pipeline accuracy and reduce false rejects across multi-camera deployments.",
    start: "2026-03-15",
    target: "2026-06-30",
    risks: ["Edge-case lighting conditions still cause occasional false rejects"],
    team: ["lena-okoye", "aarav-mehta"],
    agents: ["software-engineer-agent", "qa-engineer-agent", "customer-success-agent"],
    artifacts: [
      { label: "Requirement Document", status: "done", detail: "Accuracy target defined." },
      { label: "Product Plan", status: "done", detail: "Benchmark milestones agreed." },
      { label: "Architecture", status: "done", detail: "Pipeline tuning approach documented." },
      { label: "Tasks", status: "in-progress", detail: "Model tuning and validation in progress." },
      { label: "Test Plans", status: "in-progress", detail: "Multi-camera benchmark suite running." },
      { label: "Release", status: "pending", detail: "Pending acceptance verification." },
    ],
  },
  {
    id: "prj-4",
    slug: "hygyr-growth",
    name: "HYGYR Growth Engine",
    product: "HYGYR",
    status: "at-risk",
    health: "red",
    progress: 21,
    owner: "Marcus Feld",
    objective: "Grow quarterly revenue by 20%",
    summary:
      "Convert HYGYR free users into the broader product ecosystem through targeted growth experiments.",
    start: "2026-05-20",
    target: "2026-08-15",
    risks: [
      "Growth experiments are blocked on analytics instrumentation",
      "No engineer currently allocated to the funnel work",
    ],
    team: ["marcus-feld", "noah-bennett"],
    agents: ["marketing-agent", "sales-agent", "customer-success-agent"],
    artifacts: [
      { label: "Requirement Document", status: "in-progress", detail: "Growth hypotheses being defined." },
      { label: "Product Plan", status: "pending", detail: "Awaiting engineering allocation." },
      { label: "Architecture", status: "pending", detail: "Analytics instrumentation not scoped." },
      { label: "Tasks", status: "pending", detail: "Blocked." },
      { label: "Test Plans", status: "pending", detail: "Not started." },
      { label: "Release", status: "pending", detail: "Not scheduled." },
    ],
  },
];

export const tasks: Task[] = [
  { id: "t-1", title: "Design rollback engine state machine", projectSlug: "sentra-deployment", stage: "Released", assignee: "solution-architect-agent", type: "feature", priority: "high", updated: "2026-05-28" },
  { id: "t-2", title: "Implement endpoint rollout scheduler", projectSlug: "sentra-deployment", stage: "Code Review", assignee: "aarav-mehta", type: "feature", priority: "high", updated: "2026-06-05" },
  { id: "t-3", title: "Rollback engine core implementation", projectSlug: "sentra-deployment", stage: "In Progress", assignee: "aarav-mehta", type: "feature", priority: "critical", updated: "2026-06-06" },
  { id: "t-4", title: "Deployment audit-log regression suite", projectSlug: "sentra-deployment", stage: "Testing", assignee: "lena-okoye", type: "test", priority: "medium", updated: "2026-06-06" },
  { id: "t-5", title: "Harden release pipeline with canary stage", projectSlug: "sentra-deployment", stage: "Assigned", assignee: "sofia-haddad", type: "infra", priority: "medium", updated: "2026-06-04" },
  { id: "t-6", title: "Security review of deployment permissions", projectSlug: "sentra-deployment", stage: "Ready", assignee: "security-agent", type: "feature", priority: "high", updated: "2026-06-03" },
  { id: "t-7", title: "Write deployment module user docs", projectSlug: "sentra-deployment", stage: "Backlog", assignee: "documentation-agent", type: "docs", priority: "low", updated: "2026-06-02" },
  { id: "t-8", title: "Fix false reject on low-light frames", projectSlug: "facenova-accuracy", stage: "Approval", assignee: "qa-engineer-agent", type: "bug", priority: "high", updated: "2026-06-06" },
  { id: "t-9", title: "Tune recognition threshold per camera", projectSlug: "facenova-accuracy", stage: "In Progress", assignee: "aarav-mehta", type: "feature", priority: "high", updated: "2026-06-05" },
  { id: "t-10", title: "Multi-camera benchmark validation", projectSlug: "facenova-accuracy", stage: "Testing", assignee: "lena-okoye", type: "test", priority: "medium", updated: "2026-06-06" },
  { id: "t-11", title: "Define Unite realtime sync contract", projectSlug: "unite-launch", stage: "Planning", assignee: "solution-architect-agent", type: "feature", priority: "high", updated: "2026-06-04" },
  { id: "t-12", title: "Draft Unite beta requirements", projectSlug: "unite-launch", stage: "Ready", assignee: "diego-ramos", type: "feature", priority: "medium", updated: "2026-06-03" },
  { id: "t-13", title: "Unite launch campaign brief", projectSlug: "unite-launch", stage: "Backlog", assignee: "marcus-feld", type: "docs", priority: "low", updated: "2026-06-01" },
  { id: "t-14", title: "Instrument HYGYR conversion funnel", projectSlug: "hygyr-growth", stage: "Backlog", assignee: "marcus-feld", type: "feature", priority: "medium", updated: "2026-05-30" },
  { id: "t-15", title: "Knowledge archive: policy engine v2", projectSlug: "sentra-deployment", stage: "Knowledge Archived", assignee: "documentation-agent", type: "docs", priority: "low", updated: "2026-05-26" },
];

export const memoryRecords: MemoryRecord[] = [
  {
    id: "mem-prod-1",
    type: "product",
    title: "Why Sentra needs a deployment module",
    summary:
      "Customers manage software across thousands of endpoints but had no controlled way to roll out and roll back changes. The deployment module exists to make rollouts safe, observable, and reversible.",
    tags: ["sentra", "deployment", "rationale"],
    date: "2026-04-02",
    author: "Product Manager Agent",
    relatedProject: "sentra-deployment",
  },
  {
    id: "mem-eng-1",
    type: "engineering",
    title: "Rollback engine architecture decision",
    summary:
      "The rollback engine is modeled as a state machine with immutable deployment snapshots. This guarantees a deterministic path back to any prior known-good state.",
    tags: ["architecture", "rollback", "sentra"],
    date: "2026-04-18",
    author: "Solution Architect Agent",
    relatedProject: "sentra-deployment",
  },
  {
    id: "mem-eng-2",
    type: "engineering",
    title: "FaceNova false-reject root cause",
    summary:
      "Low-light frames degraded embedding quality. The fix introduces per-camera adaptive thresholds validated through the multi-camera benchmark suite.",
    tags: ["facenova", "accuracy", "qa"],
    date: "2026-05-22",
    author: "QA Engineer Agent",
    relatedProject: "facenova-accuracy",
  },
  {
    id: "mem-eng-3",
    type: "engineering",
    title: "Zero-downtime release strategy",
    summary:
      "Releases use a canary stage followed by progressive rollout with automated health checks, enabling instant rollback if error budgets are breached.",
    tags: ["devops", "release", "ci-cd"],
    date: "2026-03-30",
    author: "DevOps Agent",
    relatedProject: "sentra-deployment",
  },
  {
    id: "mem-cust-1",
    type: "customer",
    title: "Enterprise request: deployment audit trail",
    summary:
      "A multi-site enterprise customer requested a complete audit trail for every deployment action for compliance. This shaped the auditability requirements of the deployment module.",
    tags: ["customer", "compliance", "sentra"],
    date: "2026-04-10",
    author: "Customer Success Agent",
    relatedProject: "sentra-deployment",
  },
  {
    id: "mem-dec-1",
    type: "decision",
    title: "Decision: rebalance workload off Aarav",
    summary:
      "With Aarav owning both the rollback engine and FaceNova tuning, the Team Orchestrator flagged overload. Decision: move recognition-threshold work scheduling to reduce context switching.",
    tags: ["operations", "workload", "decision"],
    date: "2026-06-01",
    author: "Team Orchestrator Agent",
  },
  {
    id: "mem-dec-2",
    type: "decision",
    title: "Decision: deployment permissions model",
    summary:
      "Deployment actions require role-scoped approval. Decision driven by the Security Agent to prevent unauthorized production rollouts.",
    tags: ["security", "permissions", "decision"],
    date: "2026-05-12",
    author: "Security Agent",
    relatedProject: "sentra-deployment",
  },
  {
    id: "mem-biz-1",
    type: "business",
    title: "Pipeline impact of FaceNova accuracy",
    summary:
      "Higher recognition accuracy unblocked a stalled multi-site enterprise deal, contributing an estimated +18% to the quarter's expansion pipeline.",
    tags: ["revenue", "facenova", "pipeline"],
    date: "2026-05-25",
    author: "CEO Agent",
  },
  {
    id: "mem-biz-2",
    type: "business",
    title: "HYGYR as a top-of-funnel growth lever",
    summary:
      "HYGYR's free users represent the largest top-of-funnel audience. Converting even 3% into the ecosystem would materially move quarterly revenue.",
    tags: ["growth", "hygyr", "revenue"],
    date: "2026-05-18",
    author: "Marketing Agent",
  },
];

export const TASK_STAGES = [
  "Backlog",
  "Planning",
  "Ready",
  "Assigned",
  "In Progress",
  "Code Review",
  "Testing",
  "Approval",
  "Released",
  "Knowledge Archived",
] as const;

export function getEmployee(slug: string) {
  return employees.find((e) => e.slug === slug);
}

export function getAgent(slug: string) {
  return agents.find((a) => a.slug === slug);
}

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}

export function getMemory(id: string) {
  return memoryRecords.find((m) => m.id === id);
}

export function displayName(slug: string): string {
  const emp = getEmployee(slug);
  if (emp) return emp.name;
  const agent = getAgent(slug);
  if (agent) return agent.name;
  return slug;
}
