export type HeadquartersNavChild = {
  label: string;
  href: string;
};

export type HeadquartersNavItem = {
  label: string;
  href: string;
  icon: string;
  description: string;
  group?: string;
  children?: HeadquartersNavChild[];
};

export type HeadquartersNavSection = {
  title: string;
  items: HeadquartersNavItem[];
};

/** Flat headquarters navigation — single source of truth for the sidebar. */
export const HEADQUARTERS_NAV_ITEMS: HeadquartersNavItem[] = [
  {
    group: "Executive Briefing",
    label: "Founder Workspace",
    href: "/sai/founder",
    icon: "◉",
    description: "Executive headquarters and company command bridge",
  },
  {
    group: "Executive Briefing",
    label: "Records Center",
    href: "/sai/records",
    icon: "▣",
    description: "Official organizational records and history",
  },
  {
    group: "Executive Briefing",
    label: "Organization",
    href: "/sai/organization",
    icon: "⬡",
    description: "Workforce operations headquarters — live session execution",
    children: [
      { label: "Operations Center", href: "/sai/organization" },
      { label: "Active Sessions", href: "/sai/organization?section=active-sessions" },
      { label: "Agent Center", href: "/sai/organization?section=agent-center" },
      { label: "Agent Workspaces", href: "/sai/organization?section=agent-workspaces" },
      { label: "Departments", href: "/sai/organization?section=departments" },
      { label: "Employees", href: "/sai/organization?section=employees" },
      { label: "Capacity & Workload", href: "/sai/organization?section=capacity" },
      { label: "Organization Structure", href: "/sai/organization?section=structure" },
    ],
  },
  {
    group: "Company",
    label: "Projects",
    href: "/sai/projects",
    icon: "▣",
    description: "Long-term products and initiatives",
  },
  {
    group: "Company",
    label: "Customers",
    href: "/sai/customers",
    icon: "◈",
    description: "Leads, customers, opportunities, and support",
  },
  {
    group: "Execution",
    label: "Session Center",
    href: "/sai/sessions",
    icon: "⏱",
    description: "Company execution engine — sessions, duties, automation, and intelligence",
    children: [
      { label: "Dashboard", href: "/sai/sessions" },
      { label: "All Sessions", href: "/sai/sessions?section=registry-all" },
      { label: "Active", href: "/sai/sessions?section=registry-active" },
      { label: "Scheduled", href: "/sai/sessions?section=registry-scheduled" },
      { label: "Waiting Approval", href: "/sai/sessions?section=registry-approval" },
      { label: "Completed", href: "/sai/sessions?section=registry-completed" },
      { label: "Archived", href: "/sai/sessions?section=registry-archived" },
      { label: "Cancelled", href: "/sai/sessions?section=registry-cancelled" },
      { label: "Session Templates", href: "/sai/sessions?section=templates" },
      { label: "Duty Center", href: "/sai/sessions?section=duties" },
      { label: "Automation Center", href: "/sai/sessions?section=automation" },
      { label: "Agent Workspace", href: "/sai/sessions?section=agents" },
      { label: "Session Intelligence", href: "/sai/sessions?section=intelligence" },
      { label: "Analytics", href: "/sai/sessions?section=analytics" },
      { label: "Settings", href: "/sai/sessions?section=settings" },
    ],
  },
  {
    group: "Intelligence",
    label: "Analytics",
    href: "/sai/analytics",
    icon: "◆",
    description: "Revenue, delivery, growth, and performance",
  },
  {
    group: "System",
    label: "Settings",
    href: "/sai/settings",
    icon: "⚙",
    description: "Company configuration and integrations",
  },
];

/** Grouped view derived from flat nav items (for docs and legacy consumers). */
export const HEADQUARTERS_NAV: HeadquartersNavSection[] = HEADQUARTERS_NAV_ITEMS.reduce<
  HeadquartersNavSection[]
>((sections, item) => {
  const title = item.group ?? item.label;
  const last = sections[sections.length - 1];
  const entry = { label: item.label, href: item.href, icon: item.icon, description: item.description };

  if (last?.title === title) {
    last.items.push(entry);
    return sections;
  }

  sections.push({ title, items: [entry] });
  return sections;
}, []);

/** Founder-facing creation actions — tasks are generated by agents, not the founder. */
export const FOUNDER_CREATE_ACTIONS = [
  { id: "objective", label: "Objective", href: "/sai/founder?create=objective" },
  { id: "project", label: "Project", href: "/sai/projects" },
  { id: "product", label: "Product", href: "/sai/projects" },
  { id: "customer", label: "Customer", href: "/sai/customers" },
  { id: "meeting", label: "Meeting", href: "/sai/founder?tab=meetings" },
  { id: "workflow", label: "Workflow", href: "/sai/sessions?section=automation" },
  { id: "knowledge", label: "Knowledge Record", href: "/sai/records" },
] as const;

/** Legacy routes redirected to the new headquarters structure. */
export const HEADQUARTERS_LEGACY_REDIRECTS: Record<string, string> = {
  "/sai": "/sai/founder",
  "/sai/execution": "/sai/sessions",
  "/sai/control": "/sai/sessions?section=automation",
  "/sai/operations": "/sai/sessions",
  "/sai/automation": "/sai/sessions?section=automation",
  "/sai/agents": "/sai/organization?section=agent-center",
  "/sai/employees": "/sai/organization?section=employees",
  "/sai/tasks": "/sai/sessions",
  "/sai/inbox": "/sai/founder?tab=inbox",
  "/sai/timeline": "/sai/analytics",
  "/sai/memory": "/sai/records",
  "/sai/brain": "/sai/records",
  "/sai/project-memory": "/sai/sessions",
  "/sai/resources": "/sai/settings?tab=resources",
  "/sai/governance": "/sai/settings?tab=governance",
  "/sai/settings/ai": "/sai/settings?tab=ai",
  "/sai/approvals": "/sai/founder?tab=inbox",
  "/sai/releases": "/sai/sessions",
};

export const FOUNDER_DEFAULT_PATH = "/sai/founder";

/** Resolve a legacy /sai pathname to its headquarters redirect target, if any. */
export function resolveHeadquartersLegacyRedirect(pathname: string): string | null {
  return HEADQUARTERS_LEGACY_REDIRECTS[pathname] ?? null;
}
